name: Deploy Front
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v4

      # (Opcional) verificar que el .env existe
      - name: Check front .env exists
        run: ls -l /home/mudras/env/front/.env

      - name: Build FRONT image (with secret)
        working-directory: /home/mudras/front/actions-runner/_work/mudras_front/mudras_front
        run: |
          docker build \
            --secret id=front_env,src=/home/mudras/env/front/.env \
            -t mudras_front:latest .

      - name: Up FRONT with compose
        run: docker compose -f /home/mudras/deploy/mudras/docker-compose.yml up -d front

      - name: Prune old images
        run: docker image prune -f
